service: disgrafic-serverless
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:us-east-2:489034307864:table/CLIENTS
        - arn:aws:dynamodb:us-east-2:489034307864:table/PRODUCTS
  environment:
    CLIENTS_TABLE: CLIENTS
    PRODUCTS_TABLE: PRODUCTS

functions:
  clientsApi:
    handler: src/clients/index.handler
    events:
      - httpApi:
          path: /clients
          method: "*"
  productsApi:
    handler: src/products/index.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    ClientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: clientId
            AttributeType: S
        KeySchema:
          - AttributeName: clientId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: CLIENTS
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: PRODUCTS
